name: '[CI/CD] SCT CI Pipeline'
on:
  schedule: 
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions: {}
   
jobs:
  buid-containers-we-care-about:
    runs-on: ubuntu-latest
    name: Build containers relevant to SCT
    strategy:
      max-parallel: 3
      matrix:
        container: ["bitnami/os-shell", "bitnami/postgresql", "bitnami/postgres-exporter", "bitnami/redis-cluster", "bitnami/redis-exporter", "bitnami/minio", "bitnami/minio-client", "bitnami/minio-object-browser"]
    steps:
      - name: Announce Container
        run: echo "Building container ${{ matrix.container }}"
